DROP TABLE IF EXISTS users, requests, items, comments, bookings;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(64) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description VARCHAR(256) NOT NULL,
    requester_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT PK_REQUEST PRIMARY KEY (id),
    CONSTRAINT fk_requests_users_requester_id FOREIGN KEY (requester_id) REFERENCES users
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(256) NOT NULL,
    available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL,
    request_id BIGINT NOT NULL,
        CONSTRAINT PK_ITEM PRIMARY KEY (id),
        CONSTRAINT FK_ITEM_OWNER FOREIGN KEY (owner_id) references users
            on delete cascade on update cascade,
        CONSTRAINT FK_ITEM_REQUEST FOREIGN KEY (request_id) references requests
            on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    status VARCHAR(15) NOT NULL,
        CONSTRAINT PK_BOOKING PRIMARY KEY (id),
        CONSTRAINT FK_BOOKING_ITEM FOREIGN KEY (item_id) references items
            on delete cascade on update cascade,
        CONSTRAINT FK_BOOKING_BOOKER FOREIGN KEY (booker_id) references users
            on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text VARCHAR(1000) NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        CONSTRAINT PK_COMMENT PRIMARY KEY (id),
        CONSTRAINT FK_COMMENT_ITEM FOREIGN KEY (item_id) references items
            on delete cascade on update cascade,
        CONSTRAINT FK_COMMENT_AUTHOR FOREIGN KEY (author_id) references users
            on delete cascade on update cascade
);